var ascii404List = [
    "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;444444444&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;000000000&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;444444444&nbsp;&nbsp;<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;4::::::::4&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;00:::::::::00&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;4::::::::4&nbsp;&nbsp;<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;4:::::::::4&nbsp;&nbsp;&nbsp;00:::::::::::::00&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;4:::::::::4&nbsp;&nbsp;<br>&nbsp;&nbsp;&nbsp;&nbsp;4::::44::::4&nbsp;&nbsp;0:::::::000:::::::0&nbsp;&nbsp;&nbsp;&nbsp;4::::44::::4&nbsp;&nbsp;<br>&nbsp;&nbsp;&nbsp;4::::4&nbsp;4::::4&nbsp;&nbsp;0::::::0&nbsp;&nbsp;&nbsp;0::::::0&nbsp;&nbsp;&nbsp;4::::4&nbsp;4::::4&nbsp;&nbsp;<br>&nbsp;&nbsp;4::::4&nbsp;&nbsp;4::::4&nbsp;&nbsp;0:::::0&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;0:::::0&nbsp;&nbsp;4::::4&nbsp;&nbsp;4::::4&nbsp;&nbsp;<br>&nbsp;4::::4&nbsp;&nbsp;&nbsp;4::::4&nbsp;&nbsp;0:::::0&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;0:::::0&nbsp;4::::4&nbsp;&nbsp;&nbsp;4::::4&nbsp;&nbsp;<br>4::::444444::::4440:::::0&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;0:::::04::::444444::::444<br>4::::::::::::::::40:::::0&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;0:::::04::::::::::::::::4<br>4444444444:::::4440:::::0&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;0:::::04444444444:::::444<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;4::::4&nbsp;&nbsp;0:::::0&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;0:::::0&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;4::::4&nbsp;&nbsp;<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;4::::4&nbsp;&nbsp;0::::::0&nbsp;&nbsp;&nbsp;0::::::0&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;4::::4&nbsp;&nbsp;<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;4::::4&nbsp;&nbsp;0:::::::000:::::::0&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;4::::4&nbsp;&nbsp;<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;4::::4&nbsp;&nbsp;&nbsp;00:::::::::::::00&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;4::::4&nbsp;&nbsp;<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;4::::4&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;00:::::::::00&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;4::::4&nbsp;&nbsp;<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;444444&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;000000000&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;444444&nbsp;&nbsp;<br>",   
    "&nbsp;__&nbsp;&nbsp;&nbsp;&nbsp;__&nbsp;&nbsp;&nbsp;______&nbsp;&nbsp;&nbsp;__&nbsp;&nbsp;&nbsp;&nbsp;__&nbsp;<br>|&nbsp;&nbsp;\\&nbsp;&nbsp;|&nbsp;&nbsp;\\&nbsp;/&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\\&nbsp;|&nbsp;&nbsp;\\&nbsp;&nbsp;|&nbsp;&nbsp;\\<br>|&nbsp;$$&nbsp;&nbsp;|&nbsp;$$|&nbsp;&nbsp;$$$$$$\\|&nbsp;$$&nbsp;&nbsp;|&nbsp;$$<br>|&nbsp;$$__|&nbsp;$$|&nbsp;$$$\\|&nbsp;$$|&nbsp;$$__|&nbsp;$$<br>|&nbsp;$$&nbsp;&nbsp;&nbsp;&nbsp;$$|&nbsp;$$$$\\&nbsp;$$|&nbsp;$$&nbsp;&nbsp;&nbsp;&nbsp;$$<br>&nbsp;\\$$$$$$$$|&nbsp;$$\\$$\\$$&nbsp;\\$$$$$$$$<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;$$|&nbsp;$$_\\$$$$&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;$$<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;$$&nbsp;\\$$&nbsp;&nbsp;\\$$$&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;$$<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\\$$&nbsp;&nbsp;\\$$$$$$&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\\$$",                       
    "&nbsp;&nbsp;&nbsp;&nbsp;.---.&nbsp;&nbsp;&nbsp;&nbsp;.----.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.---.&nbsp;&nbsp;&nbsp;<br>&nbsp;&nbsp;&nbsp;&nbsp;/&nbsp;.&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;/&nbsp;&nbsp;..&nbsp;&nbsp;\\&nbsp;&nbsp;&nbsp;&nbsp;/&nbsp;.&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;<br>&nbsp;&nbsp;&nbsp;/&nbsp;/|&nbsp;&nbsp;|&nbsp;&nbsp;.&nbsp;&nbsp;/&nbsp;&nbsp;\\&nbsp;&nbsp;.&nbsp;&nbsp;/&nbsp;/|&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;<br>&nbsp;&nbsp;/&nbsp;/&nbsp;|&nbsp;&nbsp;|_&nbsp;|&nbsp;&nbsp;|&nbsp;&nbsp;'&nbsp;&nbsp;|&nbsp;/&nbsp;/&nbsp;|&nbsp;&nbsp;|_&nbsp;&nbsp;<br>&nbsp;/&nbsp;&nbsp;'-'&nbsp;&nbsp;&nbsp;&nbsp;|'&nbsp;&nbsp;\\&nbsp;&nbsp;/&nbsp;&nbsp;'/&nbsp;&nbsp;'-'&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;<br>&nbsp;`----|&nbsp;&nbsp;|-'&nbsp;\\&nbsp;&nbsp;`'&nbsp;&nbsp;/&nbsp;`----|&nbsp;&nbsp;|-'&nbsp;<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`--'&nbsp;&nbsp;&nbsp;&nbsp;`---''&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`--'&nbsp;&nbsp;&nbsp;",
    "&nbsp;___&nbsp;&nbsp;&nbsp;___&nbsp;&nbsp;________&nbsp;&nbsp;___&nbsp;&nbsp;&nbsp;___&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>|\\&nbsp;&nbsp;\\&nbsp;|\\&nbsp;&nbsp;\\|\\&nbsp;&nbsp;&nbsp;__&nbsp;&nbsp;\\|\\&nbsp;&nbsp;\\&nbsp;|\\&nbsp;&nbsp;\\&nbsp;&nbsp;&nbsp;&nbsp;<br>\\&nbsp;\\&nbsp;&nbsp;\\\\_\\&nbsp;&nbsp;\\&nbsp;\\&nbsp;&nbsp;\\|\\&nbsp;&nbsp;\\&nbsp;\\&nbsp;&nbsp;\\\\_\\&nbsp;&nbsp;\\&nbsp;&nbsp;&nbsp;<br>&nbsp;\\&nbsp;\\______&nbsp;&nbsp;\\&nbsp;\\&nbsp;&nbsp;\\\\\\&nbsp;&nbsp;\\&nbsp;\\______&nbsp;&nbsp;\\&nbsp;&nbsp;<br>&nbsp;&nbsp;\\|_____|\\&nbsp;&nbsp;\\&nbsp;\\&nbsp;&nbsp;\\\\\\&nbsp;&nbsp;\\|_____|\\&nbsp;&nbsp;\\&nbsp;<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\\&nbsp;\\__\\&nbsp;\\_______\\&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\\&nbsp;\\__\\<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\\|__|\\|_______|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\\|__|",
    '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;xeee&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.n~~%x.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;xeee&nbsp;&nbsp;&nbsp;&nbsp;<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;d888R&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;x88X&nbsp;&nbsp;&nbsp;888.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;d888R&nbsp;&nbsp;&nbsp;&nbsp;<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;d8888R&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;X888X&nbsp;&nbsp;&nbsp;8888L&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;d8888R&nbsp;&nbsp;&nbsp;&nbsp;<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;@&nbsp;8888R&nbsp;&nbsp;&nbsp;&nbsp;X8888X&nbsp;&nbsp;&nbsp;88888&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;@&nbsp;8888R&nbsp;&nbsp;&nbsp;&nbsp;<br>&nbsp;&nbsp;&nbsp;.P&nbsp;&nbsp;8888R&nbsp;&nbsp;&nbsp;&nbsp;88888X&nbsp;&nbsp;&nbsp;88888X&nbsp;&nbsp;&nbsp;&nbsp;.P&nbsp;&nbsp;8888R&nbsp;&nbsp;&nbsp;&nbsp;<br>&nbsp;&nbsp;:F&nbsp;&nbsp;&nbsp;8888R&nbsp;&nbsp;&nbsp;&nbsp;88888X&nbsp;&nbsp;&nbsp;88888X&nbsp;&nbsp;&nbsp;:F&nbsp;&nbsp;&nbsp;8888R&nbsp;&nbsp;&nbsp;&nbsp;<br>&nbsp;x"&nbsp;&nbsp;&nbsp;&nbsp;8888R&nbsp;&nbsp;&nbsp;&nbsp;88888X&nbsp;&nbsp;&nbsp;88888f&nbsp;&nbsp;x"&nbsp;&nbsp;&nbsp;&nbsp;8888R&nbsp;&nbsp;&nbsp;&nbsp;<br>d8eeeee88888eer&nbsp;48888X&nbsp;&nbsp;&nbsp;88888&nbsp;&nbsp;d8eeeee88888eer&nbsp;<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;8888R&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;?888X&nbsp;&nbsp;&nbsp;8888"&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;8888R&nbsp;&nbsp;&nbsp;&nbsp;<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;8888R&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"88X&nbsp;&nbsp;&nbsp;88*`&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;8888R&nbsp;&nbsp;&nbsp;&nbsp;<br>&nbsp;&nbsp;&nbsp;&nbsp;"*%%%%%%**~&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;^"==="`&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"*%%%%%%**~&nbsp;',                 
];

var randomNum = parseInt(Math.random()*(ascii404List.length),10);
                          
(function(a){
    a.fn.typewriter=function(){
        this.each(function(){
            var d = a(this), c = d.html(), b=0;
            d.html("");
            var e = setInterval(function(){
                var f = c.substr(b,1);
                if(f=="<"){
                    b=c.indexOf(">",b)+1
                } else {
                    b++
                }
                d.html(c.substring(0,b)+(b&1?"_":""));
                if(b>=c.length){
                    clearInterval(e)
                }
            },75)
        });
        return this
    }
})(mdui.$);

mdui.$("#ASCII404")[0].innerHTML = "<span>" + ascii404List[randomNum] + "</span>";
mdui.$("#code").typewriter();
          